// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// watershed_cpp
NumericMatrix watershed_cpp(NumericMatrix im, NumericMatrix priority, bool fill_lines);
RcppExport SEXP _ForestTools_watershed_cpp(SEXP imSEXP, SEXP prioritySEXP, SEXP fill_linesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type im(imSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type priority(prioritySEXP);
    Rcpp::traits::input_parameter< bool >::type fill_lines(fill_linesSEXP);
    rcpp_result_gen = Rcpp::wrap(watershed_cpp(im, priority, fill_lines));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ForestTools_watershed_cpp", (DL_FUNC) &_ForestTools_watershed_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ForestTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
