// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// glcm0
NumericMatrix glcm0(NumericMatrix x, int n_grey, int d);
RcppExport SEXP _ForestTools_glcm0(SEXP xSEXP, SEXP n_greySEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_grey(n_greySEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(glcm0(x, n_grey, d));
    return rcpp_result_gen;
END_RCPP
}
// glcm90
NumericMatrix glcm90(NumericMatrix x, int n_grey, int d);
RcppExport SEXP _ForestTools_glcm90(SEXP xSEXP, SEXP n_greySEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_grey(n_greySEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(glcm90(x, n_grey, d));
    return rcpp_result_gen;
END_RCPP
}
// glcm45
NumericMatrix glcm45(NumericMatrix x, int n_grey, int d);
RcppExport SEXP _ForestTools_glcm45(SEXP xSEXP, SEXP n_greySEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_grey(n_greySEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(glcm45(x, n_grey, d));
    return rcpp_result_gen;
END_RCPP
}
// glcm135
NumericMatrix glcm135(NumericMatrix x, int n_grey, int d);
RcppExport SEXP _ForestTools_glcm135(SEXP xSEXP, SEXP n_greySEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_grey(n_greySEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(glcm135(x, n_grey, d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ForestTools_glcm0", (DL_FUNC) &_ForestTools_glcm0, 3},
    {"_ForestTools_glcm90", (DL_FUNC) &_ForestTools_glcm90, 3},
    {"_ForestTools_glcm45", (DL_FUNC) &_ForestTools_glcm45, 3},
    {"_ForestTools_glcm135", (DL_FUNC) &_ForestTools_glcm135, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ForestTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
