# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a 0 degree GLCM
#' 
#' Used internally by glcm()
#' 
#' @param x A Numeric matrix, integer values only
#' @param n_grey Number of grey levels
#' @param d distance from reference pixel to neighbour pixel
glcm0 <- function(x, n_grey, d) {
    .Call('_ForestTools_glcm0', PACKAGE = 'ForestTools', x, n_grey, d)
}

#' Create a 90 degree GLCM
#' 
#' Used internally by glcm()
#' 
#' @param x A Numeric matrix, integer values only
#' @param n_grey Number of grey levels
#' @param d distance from reference pixel to neighbour pixel
glcm90 <- function(x, n_grey, d) {
    .Call('_ForestTools_glcm90', PACKAGE = 'ForestTools', x, n_grey, d)
}

#' Create a 45 degree GLCM
#' 
#' Used internally by glcm()
#' 
#' @param x A Numeric matrix, integer values only
#' @param n_grey Number of grey levels
#' @param d distance from reference pixel to neighbour pixel
glcm45 <- function(x, n_grey, d) {
    .Call('_ForestTools_glcm45', PACKAGE = 'ForestTools', x, n_grey, d)
}

#' Create a 135 degree GLCM
#' 
#' Used internally by glcm()
#' 
#' @param x A Numeric matrix, integer values only
#' @param n_grey Number of grey levels
#' @param d distance from reference pixel to neighbour pixel
glcm135 <- function(x, n_grey, d) {
    .Call('_ForestTools_glcm135', PACKAGE = 'ForestTools', x, n_grey, d)
}

