# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

watershed_cpp <- function(im, priority, fill_lines = TRUE) {
    .Call(`_ForestTools_watershed_cpp`, im, priority, fill_lines)
}

